
api:
  build: ./docker-files/api
  ports:
    - "3030:3030"
  volumes:
    - ./volumes/sampleapp:/srv/www/
  command: bash -c "cd /srv/www && npm install && node /srv/www/server.js"
  links:
    - mongodb
nginx:
    build: ./docker-files/nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
        - node4:node4
        - api:api
    ports:
        - "80:80"
node1:
    build: ./docker-files/app-one
    links:
        - mongodb
    ports:
        - "4000"
node2:
    build: ./docker-files/app-two
    links:
        - mongodb
    ports:
        - "7000"
node3:
    build: ./docker-files/app-three
    links:
        - mongodb
    ports:
        - "3000"
node4:
    build: ./docker-files/app-four
    links:
        - mongodb
    ports:
        - "5000"

mongodb:
  image: mongo
  ports: 
   - "27017:27017"
  environment:
    MONGODB_PASS: password

