

init:
    build: ./docker-files/init
nginx:
    build: ./docker-files/nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
        - node4:node4
    ports:
        - "80:80"
node1:
    build: ./docker-files/app-one
    links:
        - redis
        - mongodb
    ports:
        - "3000"
node2:
    build: ./docker-files/app-two
    links:
        - redis
        - mongodb
    ports:
        - "4000"
node3:
    build: ./docker-files/app-three
    links:
        - redis
        - mongodb
    ports:
        - "5000"
node4:
    build: ./docker-files/app-four
    links:
        - redis
        - mongodb
    ports:
        - "8000"
redis:
    image: redis
    ports:
        - "6379"
redis:
  image: redis

mongodb:
  image: mongo
  ports: 
   - "27017:27017"
  environment:
    MONGODB_PASS: password

elasticsearch:
  image: elasticsearch
  ports:
    - "9201:9201"
    - "9301:9301"
